module.exports = {
  PARAMETER_MISSING: "PARAMETER_MISSING",
  VALIDATION: "VALIDATION",
  NOT_FOUND: "NOT_FOUND",
  CANNOT_BE_BLANK: "CANNOT_BE_BLANK",
  DUPLICATE_ID: "DUPLICATE_ID",
  INVALID_PARAMETER: "INVALID_PARAMETER"
};
